### ISSUE TITLE
This is cool - but a thought:

### ISSUE THREAD

**Issue by shadowcat-mst** [srchulo/Mus#1]
(note I already tweeted liking this and suggesting it should be in Mu's see also)

but:

    use strictures 2;
    use Import::Into;
    
    use Mu ();
    use MooX::StrictConstructor ();
    
    sub import {
        my $caller = caller;
        $_->import::into( $caller ) for qw/ Mu MooX::StrictConstructor /;
    }

as of Import::Into version 1.002003 - 2014-07-09

can be shortened to:

    use strictures 2;
    use Import::Into;
    
    sub import {
        $_->import::into( 1 ) for qw/ Mu MooX::StrictConstructor /;
    }

which would be even more elegant and makes me wonder if you couldn't have a MuX ala MooX that allows for importing the main thing plus features ... but *eh*, I accidentally invented Mu and somehow convinced @mithaldu to implement it but I'm not the BDFL of *your* code.

Either way, cool thing to have exist and I hope the shortened code is useful (I do wonder why you don't import strictures 2 in as well if you're going for maximum strictness but I wouldn't be surprised if the answer is "you don't like to push strictures' maximum strictness on your users" which is 100% fair)

**Comment by srchulo** [comment]
Hey, thanks for the suggestion! That definitely makes it cleaner, and I just made that change here along with the release on MetaCPAN:

https://github.com/srchulo/Mus/commit/77cac56e9f7ffa43f5bd3a0b31320432b270c3fd
https://metacpan.org/release/SRCHULO/Mus-0.02

And on the topic of MuX, using MooX::StrictConstructor along with Mu works, I was just inspired by Mu and wanted less typing :)

And you're right about strictures. The main purpose of my module was to enforce strict constructors, but I didn't want to force strictures on consumers of the module.

I appreciate the feedback! I'm gonna close this, but please let me know if there's anything else on your mind.
